-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.usuarios
(
    id serial,
    cedula character varying(10),
    nombre character varying(255),
    apellidos character varying(255),
    correo_electronico character varying(255),
    telefono character varying(255),
    clave character varying(255),
    cargo_id integer,
    estatus_id integer,
    fecha_hora_creacion timestamp with time zone DEFAULT NOW(),
    fecha_hora_actualizacion timestamp with time zone DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cargos
(
    id serial,
    nombre character varying(255),
    descripcion character varying(255),
    fecha_hora_creacion timestamp with time zone DEFAULT NOW(),
    fecha_hora_actualizacion time with time zone DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estatus
(
    id serial,
    nombre character varying(255),
    descripcion character varying(255),
    fecha_hora_creacion timestamp with time zone DEFAULT NOW(),
    fecha_hora_actaulizacion timestamp with time zone DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.areas_de_incidencia
(
    id serial,
    nombre character varying(255),
    descripcion character varying(255),
    fecha_hora_creacion timestamp with time zone DEFAULT NOW(),
    fecha_hora_actualizacion timestamp with time zone DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tipos_de_incidencia
(
    id serial,
    area_id integer,
    nombre character varying(255),
    descripcion character varying(255),
    fecha_hora_creacion timestamp with time zone DEFAULT NOW(),
    fecha_hora_actualizacion timestamp with time zone DEFAULT NOW(),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.incidencias
(
    id serial,
    tipo_id integer,
    usuario_id integer,
    fecha_hora_creacion timestamp with time zone DEFAULT NOW(),
    fecha_hora_actualizacion timestamp with time zone DEFAULT NOW(),
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.usuarios
    ADD FOREIGN KEY (cargo_id)
    REFERENCES public.cargos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuarios
    ADD FOREIGN KEY (estatus_id)
    REFERENCES public.estatus (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tipos_de_incidencia
    ADD FOREIGN KEY (area_id)
    REFERENCES public.areas_de_incidencia (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.incidencias
    ADD FOREIGN KEY (tipo_id)
    REFERENCES public.tipos_de_incidencia (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;